name: Publish Container with Buildpacks

on:
  push:
    branches: [main, develop]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # 1.0.0
      - "[0-9]+.[0-9]+.[0-9]+-*" # 1.0.0-alpha, 1.0.0-beta.1
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main, develop]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-tests:
    name: Check Test Results
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run'
    outputs:
      tests-passed: ${{ steps.check.outputs.tests-passed }}

    steps:
      - name: Check test workflow result
        id: check
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "tests-passed=true" >> $GITHUB_OUTPUT
            echo "✅ Tests passed, proceeding with publish"
          else
            echo "tests-passed=false" >> $GITHUB_OUTPUT
            echo "❌ Tests failed, skipping publish"
            exit 1
          fi

  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: check-tests
    if: |
      always() && (
        github.event_name == 'push' ||
        (github.event_name == 'workflow_run' && needs.check-tests.outputs.tests-passed == 'true')
      )
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}

      - name: Setup Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.7.2

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

      - name: Build with buildpacks
        run: |
          SHA="${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}"
          pack build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${SHA:0:7} \
            --builder paketobuildpacks/builder-jammy-base \
            --env BP_NODE_VERSION=20 \
            --env NODE_ENV=production \
            --publish

      - name: Tag additional versions
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          SHA="${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}"
          BASE_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${SHA:0:7}"

          echo "Tagging additional versions..."
          echo "$TAGS" | while IFS= read -r tag; do
            if [ -n "$tag" ] && [ "$tag" != "$BASE_IMAGE" ]; then
              echo "Tagging as: $tag"
              docker tag "$BASE_IMAGE" "$tag"
              docker push "$tag"
            fi
          done

      - name: Run security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
          format: "sarif"
          output: "trivy-results.sarif"
        continue-on-error: true

      - name: Upload security results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
        continue-on-error: true

      - name: Show published tags
        run: |
          echo "🎉 Successfully published container!"
          echo ""
          echo "📦 Available at:"
          echo "${{ steps.meta.outputs.tags }}" | while IFS= read -r tag; do
            if [ -n "$tag" ]; then
              echo "  - $tag"
            fi
          done
          echo ""
          if [ "${{ github.event_name }}" == "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME="${{ github.ref_name }}"
            echo "🏷️ Release: $TAG_NAME"
            echo "🐳 Docker pull: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG_NAME"
          fi
