# Quick feedback workflow for faster development
name: Quick Check

on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  quick-tests:
    name: Quick Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run typecheck
        continue-on-error: true

      - name: Lint
        run: bun run lint
        continue-on-error: true

      - name: Run unit tests only
        run: bun run test:unit

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Quick unit tests passed! Integration tests will run on the full test workflow.'
            })
